//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EB_DOTNET_SOAP_CliCon.ServicioEB {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioEB.WSEurekaSoap")]
    public interface WSEurekaSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validarIngreso", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string validarIngreso(string usuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validarIngreso", ReplyAction="*")]
        System.Threading.Tasks.Task<string> validarIngresoAsync(string usuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/traerMovimientos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EB_DOTNET_SOAP_CliCon.ServicioEB.movimiento[] traerMovimientos(string cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/traerMovimientos", ReplyAction="*")]
        System.Threading.Tasks.Task<EB_DOTNET_SOAP_CliCon.ServicioEB.movimiento[]> traerMovimientosAsync(string cuenta);
        
        // CODEGEN: El parámetro 'OperacionCuentaResponse' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/regDeposito", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="OperacionCuentaResponse")]
        EB_DOTNET_SOAP_CliCon.ServicioEB.regDepositoResponse regDeposito(EB_DOTNET_SOAP_CliCon.ServicioEB.regDepositoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/regDeposito", ReplyAction="*")]
        System.Threading.Tasks.Task<EB_DOTNET_SOAP_CliCon.ServicioEB.regDepositoResponse> regDepositoAsync(EB_DOTNET_SOAP_CliCon.ServicioEB.regDepositoRequest request);
        
        // CODEGEN: El parámetro 'OperacionCuentaResponse' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/regRetiro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="OperacionCuentaResponse")]
        EB_DOTNET_SOAP_CliCon.ServicioEB.regRetiroResponse regRetiro(EB_DOTNET_SOAP_CliCon.ServicioEB.regRetiroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/regRetiro", ReplyAction="*")]
        System.Threading.Tasks.Task<EB_DOTNET_SOAP_CliCon.ServicioEB.regRetiroResponse> regRetiroAsync(EB_DOTNET_SOAP_CliCon.ServicioEB.regRetiroRequest request);
        
        // CODEGEN: El parámetro 'OperacionCuentaResponse' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/regTransferencia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="OperacionCuentaResponse")]
        EB_DOTNET_SOAP_CliCon.ServicioEB.regTransferenciaResponse regTransferencia(EB_DOTNET_SOAP_CliCon.ServicioEB.regTransferenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/regTransferencia", ReplyAction="*")]
        System.Threading.Tasks.Task<EB_DOTNET_SOAP_CliCon.ServicioEB.regTransferenciaResponse> regTransferenciaAsync(EB_DOTNET_SOAP_CliCon.ServicioEB.regTransferenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/probarConexion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string probarConexion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/probarConexion", ReplyAction="*")]
        System.Threading.Tasks.Task<string> probarConexionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/verificarTablas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string verificarTablas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/verificarTablas", ReplyAction="*")]
        System.Threading.Tasks.Task<string> verificarTablasAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class movimiento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cuentaField;
        
        private int nromovField;
        
        private System.DateTime fechaField;
        
        private string tipoField;
        
        private string accionField;
        
        private decimal importeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string cuenta {
            get {
                return this.cuentaField;
            }
            set {
                this.cuentaField = value;
                this.RaisePropertyChanged("cuenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int nromov {
            get {
                return this.nromovField;
            }
            set {
                this.nromovField = value;
                this.RaisePropertyChanged("nromov");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string accion {
            get {
                return this.accionField;
            }
            set {
                this.accionField = value;
                this.RaisePropertyChanged("accion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal importe {
            get {
                return this.importeField;
            }
            set {
                this.importeField = value;
                this.RaisePropertyChanged("importe");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OperacionCuentaResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int estadoField;
        
        private decimal saldoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal saldo {
            get {
                return this.saldoField;
            }
            set {
                this.saldoField = value;
                this.RaisePropertyChanged("saldo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="regDeposito", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class regDepositoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string cuenta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public decimal importe;
        
        public regDepositoRequest() {
        }
        
        public regDepositoRequest(string cuenta, decimal importe) {
            this.cuenta = cuenta;
            this.importe = importe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="regDepositoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class regDepositoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EB_DOTNET_SOAP_CliCon.ServicioEB.OperacionCuentaResponse OperacionCuentaResponse;
        
        public regDepositoResponse() {
        }
        
        public regDepositoResponse(EB_DOTNET_SOAP_CliCon.ServicioEB.OperacionCuentaResponse OperacionCuentaResponse) {
            this.OperacionCuentaResponse = OperacionCuentaResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="regRetiro", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class regRetiroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string cuenta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public decimal importe;
        
        public regRetiroRequest() {
        }
        
        public regRetiroRequest(string cuenta, decimal importe) {
            this.cuenta = cuenta;
            this.importe = importe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="regRetiroResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class regRetiroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EB_DOTNET_SOAP_CliCon.ServicioEB.OperacionCuentaResponse OperacionCuentaResponse;
        
        public regRetiroResponse() {
        }
        
        public regRetiroResponse(EB_DOTNET_SOAP_CliCon.ServicioEB.OperacionCuentaResponse OperacionCuentaResponse) {
            this.OperacionCuentaResponse = OperacionCuentaResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="regTransferencia", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class regTransferenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string cuentaOrigen;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string cuentaDestino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public decimal importe;
        
        public regTransferenciaRequest() {
        }
        
        public regTransferenciaRequest(string cuentaOrigen, string cuentaDestino, decimal importe) {
            this.cuentaOrigen = cuentaOrigen;
            this.cuentaDestino = cuentaDestino;
            this.importe = importe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="regTransferenciaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class regTransferenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public EB_DOTNET_SOAP_CliCon.ServicioEB.OperacionCuentaResponse OperacionCuentaResponse;
        
        public regTransferenciaResponse() {
        }
        
        public regTransferenciaResponse(EB_DOTNET_SOAP_CliCon.ServicioEB.OperacionCuentaResponse OperacionCuentaResponse) {
            this.OperacionCuentaResponse = OperacionCuentaResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSEurekaSoapChannel : EB_DOTNET_SOAP_CliCon.ServicioEB.WSEurekaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSEurekaSoapClient : System.ServiceModel.ClientBase<EB_DOTNET_SOAP_CliCon.ServicioEB.WSEurekaSoap>, EB_DOTNET_SOAP_CliCon.ServicioEB.WSEurekaSoap {
        
        public WSEurekaSoapClient() {
        }
        
        public WSEurekaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSEurekaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSEurekaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSEurekaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string validarIngreso(string usuario, string password) {
            return base.Channel.validarIngreso(usuario, password);
        }
        
        public System.Threading.Tasks.Task<string> validarIngresoAsync(string usuario, string password) {
            return base.Channel.validarIngresoAsync(usuario, password);
        }
        
        public EB_DOTNET_SOAP_CliCon.ServicioEB.movimiento[] traerMovimientos(string cuenta) {
            return base.Channel.traerMovimientos(cuenta);
        }
        
        public System.Threading.Tasks.Task<EB_DOTNET_SOAP_CliCon.ServicioEB.movimiento[]> traerMovimientosAsync(string cuenta) {
            return base.Channel.traerMovimientosAsync(cuenta);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EB_DOTNET_SOAP_CliCon.ServicioEB.regDepositoResponse EB_DOTNET_SOAP_CliCon.ServicioEB.WSEurekaSoap.regDeposito(EB_DOTNET_SOAP_CliCon.ServicioEB.regDepositoRequest request) {
            return base.Channel.regDeposito(request);
        }
        
        public EB_DOTNET_SOAP_CliCon.ServicioEB.OperacionCuentaResponse regDeposito(string cuenta, decimal importe) {
            EB_DOTNET_SOAP_CliCon.ServicioEB.regDepositoRequest inValue = new EB_DOTNET_SOAP_CliCon.ServicioEB.regDepositoRequest();
            inValue.cuenta = cuenta;
            inValue.importe = importe;
            EB_DOTNET_SOAP_CliCon.ServicioEB.regDepositoResponse retVal = ((EB_DOTNET_SOAP_CliCon.ServicioEB.WSEurekaSoap)(this)).regDeposito(inValue);
            return retVal.OperacionCuentaResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EB_DOTNET_SOAP_CliCon.ServicioEB.regDepositoResponse> EB_DOTNET_SOAP_CliCon.ServicioEB.WSEurekaSoap.regDepositoAsync(EB_DOTNET_SOAP_CliCon.ServicioEB.regDepositoRequest request) {
            return base.Channel.regDepositoAsync(request);
        }
        
        public System.Threading.Tasks.Task<EB_DOTNET_SOAP_CliCon.ServicioEB.regDepositoResponse> regDepositoAsync(string cuenta, decimal importe) {
            EB_DOTNET_SOAP_CliCon.ServicioEB.regDepositoRequest inValue = new EB_DOTNET_SOAP_CliCon.ServicioEB.regDepositoRequest();
            inValue.cuenta = cuenta;
            inValue.importe = importe;
            return ((EB_DOTNET_SOAP_CliCon.ServicioEB.WSEurekaSoap)(this)).regDepositoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EB_DOTNET_SOAP_CliCon.ServicioEB.regRetiroResponse EB_DOTNET_SOAP_CliCon.ServicioEB.WSEurekaSoap.regRetiro(EB_DOTNET_SOAP_CliCon.ServicioEB.regRetiroRequest request) {
            return base.Channel.regRetiro(request);
        }
        
        public EB_DOTNET_SOAP_CliCon.ServicioEB.OperacionCuentaResponse regRetiro(string cuenta, decimal importe) {
            EB_DOTNET_SOAP_CliCon.ServicioEB.regRetiroRequest inValue = new EB_DOTNET_SOAP_CliCon.ServicioEB.regRetiroRequest();
            inValue.cuenta = cuenta;
            inValue.importe = importe;
            EB_DOTNET_SOAP_CliCon.ServicioEB.regRetiroResponse retVal = ((EB_DOTNET_SOAP_CliCon.ServicioEB.WSEurekaSoap)(this)).regRetiro(inValue);
            return retVal.OperacionCuentaResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EB_DOTNET_SOAP_CliCon.ServicioEB.regRetiroResponse> EB_DOTNET_SOAP_CliCon.ServicioEB.WSEurekaSoap.regRetiroAsync(EB_DOTNET_SOAP_CliCon.ServicioEB.regRetiroRequest request) {
            return base.Channel.regRetiroAsync(request);
        }
        
        public System.Threading.Tasks.Task<EB_DOTNET_SOAP_CliCon.ServicioEB.regRetiroResponse> regRetiroAsync(string cuenta, decimal importe) {
            EB_DOTNET_SOAP_CliCon.ServicioEB.regRetiroRequest inValue = new EB_DOTNET_SOAP_CliCon.ServicioEB.regRetiroRequest();
            inValue.cuenta = cuenta;
            inValue.importe = importe;
            return ((EB_DOTNET_SOAP_CliCon.ServicioEB.WSEurekaSoap)(this)).regRetiroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EB_DOTNET_SOAP_CliCon.ServicioEB.regTransferenciaResponse EB_DOTNET_SOAP_CliCon.ServicioEB.WSEurekaSoap.regTransferencia(EB_DOTNET_SOAP_CliCon.ServicioEB.regTransferenciaRequest request) {
            return base.Channel.regTransferencia(request);
        }
        
        public EB_DOTNET_SOAP_CliCon.ServicioEB.OperacionCuentaResponse regTransferencia(string cuentaOrigen, string cuentaDestino, decimal importe) {
            EB_DOTNET_SOAP_CliCon.ServicioEB.regTransferenciaRequest inValue = new EB_DOTNET_SOAP_CliCon.ServicioEB.regTransferenciaRequest();
            inValue.cuentaOrigen = cuentaOrigen;
            inValue.cuentaDestino = cuentaDestino;
            inValue.importe = importe;
            EB_DOTNET_SOAP_CliCon.ServicioEB.regTransferenciaResponse retVal = ((EB_DOTNET_SOAP_CliCon.ServicioEB.WSEurekaSoap)(this)).regTransferencia(inValue);
            return retVal.OperacionCuentaResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EB_DOTNET_SOAP_CliCon.ServicioEB.regTransferenciaResponse> EB_DOTNET_SOAP_CliCon.ServicioEB.WSEurekaSoap.regTransferenciaAsync(EB_DOTNET_SOAP_CliCon.ServicioEB.regTransferenciaRequest request) {
            return base.Channel.regTransferenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<EB_DOTNET_SOAP_CliCon.ServicioEB.regTransferenciaResponse> regTransferenciaAsync(string cuentaOrigen, string cuentaDestino, decimal importe) {
            EB_DOTNET_SOAP_CliCon.ServicioEB.regTransferenciaRequest inValue = new EB_DOTNET_SOAP_CliCon.ServicioEB.regTransferenciaRequest();
            inValue.cuentaOrigen = cuentaOrigen;
            inValue.cuentaDestino = cuentaDestino;
            inValue.importe = importe;
            return ((EB_DOTNET_SOAP_CliCon.ServicioEB.WSEurekaSoap)(this)).regTransferenciaAsync(inValue);
        }
        
        public string probarConexion() {
            return base.Channel.probarConexion();
        }
        
        public System.Threading.Tasks.Task<string> probarConexionAsync() {
            return base.Channel.probarConexionAsync();
        }
        
        public string verificarTablas() {
            return base.Channel.verificarTablas();
        }
        
        public System.Threading.Tasks.Task<string> verificarTablasAsync() {
            return base.Channel.verificarTablasAsync();
        }
    }
}
