//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EB_DOTNET_SOAP_CliCon.ServicioEB {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Movimiento", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Movimiento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CuentaField;
        
        private int NroMovField;
        
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccionField;
        
        private double ImporteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Cuenta {
            get {
                return this.CuentaField;
            }
            set {
                if ((object.ReferenceEquals(this.CuentaField, value) != true)) {
                    this.CuentaField = value;
                    this.RaisePropertyChanged("Cuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int NroMov {
            get {
                return this.NroMovField;
            }
            set {
                if ((this.NroMovField.Equals(value) != true)) {
                    this.NroMovField = value;
                    this.RaisePropertyChanged("NroMov");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Accion {
            get {
                return this.AccionField;
            }
            set {
                if ((object.ReferenceEquals(this.AccionField, value) != true)) {
                    this.AccionField = value;
                    this.RaisePropertyChanged("Accion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double Importe {
            get {
                return this.ImporteField;
            }
            set {
                if ((this.ImporteField.Equals(value) != true)) {
                    this.ImporteField = value;
                    this.RaisePropertyChanged("Importe");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioEB.EurekaServiceSoap")]
    public interface EurekaServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidarIngreso", ReplyAction="*")]
        EB_DOTNET_SOAP_CliCon.ServicioEB.ValidarIngresoResponse ValidarIngreso(EB_DOTNET_SOAP_CliCon.ServicioEB.ValidarIngresoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidarIngreso", ReplyAction="*")]
        System.Threading.Tasks.Task<EB_DOTNET_SOAP_CliCon.ServicioEB.ValidarIngresoResponse> ValidarIngresoAsync(EB_DOTNET_SOAP_CliCon.ServicioEB.ValidarIngresoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cuenta del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerMovimientos", ReplyAction="*")]
        EB_DOTNET_SOAP_CliCon.ServicioEB.TraerMovimientosResponse TraerMovimientos(EB_DOTNET_SOAP_CliCon.ServicioEB.TraerMovimientosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerMovimientos", ReplyAction="*")]
        System.Threading.Tasks.Task<EB_DOTNET_SOAP_CliCon.ServicioEB.TraerMovimientosResponse> TraerMovimientosAsync(EB_DOTNET_SOAP_CliCon.ServicioEB.TraerMovimientosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cuenta del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarDeposito", ReplyAction="*")]
        EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarDepositoResponse RegistrarDeposito(EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarDepositoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarDeposito", ReplyAction="*")]
        System.Threading.Tasks.Task<EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarDepositoResponse> RegistrarDepositoAsync(EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarDepositoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cuenta del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarRetiro", ReplyAction="*")]
        EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarRetiroResponse RegistrarRetiro(EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarRetiroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarRetiro", ReplyAction="*")]
        System.Threading.Tasks.Task<EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarRetiroResponse> RegistrarRetiroAsync(EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarRetiroRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cuentaOrigen del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarTransferencia", ReplyAction="*")]
        EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarTransferenciaResponse RegistrarTransferencia(EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarTransferenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarTransferencia", ReplyAction="*")]
        System.Threading.Tasks.Task<EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarTransferenciaResponse> RegistrarTransferenciaAsync(EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarTransferenciaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarIngresoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarIngreso", Namespace="http://tempuri.org/", Order=0)]
        public EB_DOTNET_SOAP_CliCon.ServicioEB.ValidarIngresoRequestBody Body;
        
        public ValidarIngresoRequest() {
        }
        
        public ValidarIngresoRequest(EB_DOTNET_SOAP_CliCon.ServicioEB.ValidarIngresoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarIngresoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public ValidarIngresoRequestBody() {
        }
        
        public ValidarIngresoRequestBody(string usuario, string password) {
            this.usuario = usuario;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarIngresoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarIngresoResponse", Namespace="http://tempuri.org/", Order=0)]
        public EB_DOTNET_SOAP_CliCon.ServicioEB.ValidarIngresoResponseBody Body;
        
        public ValidarIngresoResponse() {
        }
        
        public ValidarIngresoResponse(EB_DOTNET_SOAP_CliCon.ServicioEB.ValidarIngresoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarIngresoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ValidarIngresoResult;
        
        public ValidarIngresoResponseBody() {
        }
        
        public ValidarIngresoResponseBody(string ValidarIngresoResult) {
            this.ValidarIngresoResult = ValidarIngresoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TraerMovimientosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TraerMovimientos", Namespace="http://tempuri.org/", Order=0)]
        public EB_DOTNET_SOAP_CliCon.ServicioEB.TraerMovimientosRequestBody Body;
        
        public TraerMovimientosRequest() {
        }
        
        public TraerMovimientosRequest(EB_DOTNET_SOAP_CliCon.ServicioEB.TraerMovimientosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TraerMovimientosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cuenta;
        
        public TraerMovimientosRequestBody() {
        }
        
        public TraerMovimientosRequestBody(string cuenta) {
            this.cuenta = cuenta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TraerMovimientosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TraerMovimientosResponse", Namespace="http://tempuri.org/", Order=0)]
        public EB_DOTNET_SOAP_CliCon.ServicioEB.TraerMovimientosResponseBody Body;
        
        public TraerMovimientosResponse() {
        }
        
        public TraerMovimientosResponse(EB_DOTNET_SOAP_CliCon.ServicioEB.TraerMovimientosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TraerMovimientosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public EB_DOTNET_SOAP_CliCon.ServicioEB.Movimiento[] TraerMovimientosResult;
        
        public TraerMovimientosResponseBody() {
        }
        
        public TraerMovimientosResponseBody(EB_DOTNET_SOAP_CliCon.ServicioEB.Movimiento[] TraerMovimientosResult) {
            this.TraerMovimientosResult = TraerMovimientosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarDepositoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarDeposito", Namespace="http://tempuri.org/", Order=0)]
        public EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarDepositoRequestBody Body;
        
        public RegistrarDepositoRequest() {
        }
        
        public RegistrarDepositoRequest(EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarDepositoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarDepositoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cuenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double importe;
        
        public RegistrarDepositoRequestBody() {
        }
        
        public RegistrarDepositoRequestBody(string cuenta, double importe) {
            this.cuenta = cuenta;
            this.importe = importe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarDepositoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarDepositoResponse", Namespace="http://tempuri.org/", Order=0)]
        public EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarDepositoResponseBody Body;
        
        public RegistrarDepositoResponse() {
        }
        
        public RegistrarDepositoResponse(EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarDepositoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarDepositoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RegistrarDepositoResult;
        
        public RegistrarDepositoResponseBody() {
        }
        
        public RegistrarDepositoResponseBody(string RegistrarDepositoResult) {
            this.RegistrarDepositoResult = RegistrarDepositoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarRetiroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarRetiro", Namespace="http://tempuri.org/", Order=0)]
        public EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarRetiroRequestBody Body;
        
        public RegistrarRetiroRequest() {
        }
        
        public RegistrarRetiroRequest(EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarRetiroRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarRetiroRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cuenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double importe;
        
        public RegistrarRetiroRequestBody() {
        }
        
        public RegistrarRetiroRequestBody(string cuenta, double importe) {
            this.cuenta = cuenta;
            this.importe = importe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarRetiroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarRetiroResponse", Namespace="http://tempuri.org/", Order=0)]
        public EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarRetiroResponseBody Body;
        
        public RegistrarRetiroResponse() {
        }
        
        public RegistrarRetiroResponse(EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarRetiroResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarRetiroResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RegistrarRetiroResult;
        
        public RegistrarRetiroResponseBody() {
        }
        
        public RegistrarRetiroResponseBody(string RegistrarRetiroResult) {
            this.RegistrarRetiroResult = RegistrarRetiroResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarTransferenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarTransferencia", Namespace="http://tempuri.org/", Order=0)]
        public EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarTransferenciaRequestBody Body;
        
        public RegistrarTransferenciaRequest() {
        }
        
        public RegistrarTransferenciaRequest(EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarTransferenciaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarTransferenciaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cuentaOrigen;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string cuentaDestino;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double importe;
        
        public RegistrarTransferenciaRequestBody() {
        }
        
        public RegistrarTransferenciaRequestBody(string cuentaOrigen, string cuentaDestino, double importe) {
            this.cuentaOrigen = cuentaOrigen;
            this.cuentaDestino = cuentaDestino;
            this.importe = importe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarTransferenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarTransferenciaResponse", Namespace="http://tempuri.org/", Order=0)]
        public EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarTransferenciaResponseBody Body;
        
        public RegistrarTransferenciaResponse() {
        }
        
        public RegistrarTransferenciaResponse(EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarTransferenciaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarTransferenciaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RegistrarTransferenciaResult;
        
        public RegistrarTransferenciaResponseBody() {
        }
        
        public RegistrarTransferenciaResponseBody(string RegistrarTransferenciaResult) {
            this.RegistrarTransferenciaResult = RegistrarTransferenciaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EurekaServiceSoapChannel : EB_DOTNET_SOAP_CliCon.ServicioEB.EurekaServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EurekaServiceSoapClient : System.ServiceModel.ClientBase<EB_DOTNET_SOAP_CliCon.ServicioEB.EurekaServiceSoap>, EB_DOTNET_SOAP_CliCon.ServicioEB.EurekaServiceSoap {
        
        public EurekaServiceSoapClient() {
        }
        
        public EurekaServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EurekaServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EurekaServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EurekaServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EB_DOTNET_SOAP_CliCon.ServicioEB.ValidarIngresoResponse EB_DOTNET_SOAP_CliCon.ServicioEB.EurekaServiceSoap.ValidarIngreso(EB_DOTNET_SOAP_CliCon.ServicioEB.ValidarIngresoRequest request) {
            return base.Channel.ValidarIngreso(request);
        }
        
        public string ValidarIngreso(string usuario, string password) {
            EB_DOTNET_SOAP_CliCon.ServicioEB.ValidarIngresoRequest inValue = new EB_DOTNET_SOAP_CliCon.ServicioEB.ValidarIngresoRequest();
            inValue.Body = new EB_DOTNET_SOAP_CliCon.ServicioEB.ValidarIngresoRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            EB_DOTNET_SOAP_CliCon.ServicioEB.ValidarIngresoResponse retVal = ((EB_DOTNET_SOAP_CliCon.ServicioEB.EurekaServiceSoap)(this)).ValidarIngreso(inValue);
            return retVal.Body.ValidarIngresoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EB_DOTNET_SOAP_CliCon.ServicioEB.ValidarIngresoResponse> EB_DOTNET_SOAP_CliCon.ServicioEB.EurekaServiceSoap.ValidarIngresoAsync(EB_DOTNET_SOAP_CliCon.ServicioEB.ValidarIngresoRequest request) {
            return base.Channel.ValidarIngresoAsync(request);
        }
        
        public System.Threading.Tasks.Task<EB_DOTNET_SOAP_CliCon.ServicioEB.ValidarIngresoResponse> ValidarIngresoAsync(string usuario, string password) {
            EB_DOTNET_SOAP_CliCon.ServicioEB.ValidarIngresoRequest inValue = new EB_DOTNET_SOAP_CliCon.ServicioEB.ValidarIngresoRequest();
            inValue.Body = new EB_DOTNET_SOAP_CliCon.ServicioEB.ValidarIngresoRequestBody();
            inValue.Body.usuario = usuario;
            inValue.Body.password = password;
            return ((EB_DOTNET_SOAP_CliCon.ServicioEB.EurekaServiceSoap)(this)).ValidarIngresoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EB_DOTNET_SOAP_CliCon.ServicioEB.TraerMovimientosResponse EB_DOTNET_SOAP_CliCon.ServicioEB.EurekaServiceSoap.TraerMovimientos(EB_DOTNET_SOAP_CliCon.ServicioEB.TraerMovimientosRequest request) {
            return base.Channel.TraerMovimientos(request);
        }
        
        public EB_DOTNET_SOAP_CliCon.ServicioEB.Movimiento[] TraerMovimientos(string cuenta) {
            EB_DOTNET_SOAP_CliCon.ServicioEB.TraerMovimientosRequest inValue = new EB_DOTNET_SOAP_CliCon.ServicioEB.TraerMovimientosRequest();
            inValue.Body = new EB_DOTNET_SOAP_CliCon.ServicioEB.TraerMovimientosRequestBody();
            inValue.Body.cuenta = cuenta;
            EB_DOTNET_SOAP_CliCon.ServicioEB.TraerMovimientosResponse retVal = ((EB_DOTNET_SOAP_CliCon.ServicioEB.EurekaServiceSoap)(this)).TraerMovimientos(inValue);
            return retVal.Body.TraerMovimientosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EB_DOTNET_SOAP_CliCon.ServicioEB.TraerMovimientosResponse> EB_DOTNET_SOAP_CliCon.ServicioEB.EurekaServiceSoap.TraerMovimientosAsync(EB_DOTNET_SOAP_CliCon.ServicioEB.TraerMovimientosRequest request) {
            return base.Channel.TraerMovimientosAsync(request);
        }
        
        public System.Threading.Tasks.Task<EB_DOTNET_SOAP_CliCon.ServicioEB.TraerMovimientosResponse> TraerMovimientosAsync(string cuenta) {
            EB_DOTNET_SOAP_CliCon.ServicioEB.TraerMovimientosRequest inValue = new EB_DOTNET_SOAP_CliCon.ServicioEB.TraerMovimientosRequest();
            inValue.Body = new EB_DOTNET_SOAP_CliCon.ServicioEB.TraerMovimientosRequestBody();
            inValue.Body.cuenta = cuenta;
            return ((EB_DOTNET_SOAP_CliCon.ServicioEB.EurekaServiceSoap)(this)).TraerMovimientosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarDepositoResponse EB_DOTNET_SOAP_CliCon.ServicioEB.EurekaServiceSoap.RegistrarDeposito(EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarDepositoRequest request) {
            return base.Channel.RegistrarDeposito(request);
        }
        
        public string RegistrarDeposito(string cuenta, double importe) {
            EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarDepositoRequest inValue = new EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarDepositoRequest();
            inValue.Body = new EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarDepositoRequestBody();
            inValue.Body.cuenta = cuenta;
            inValue.Body.importe = importe;
            EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarDepositoResponse retVal = ((EB_DOTNET_SOAP_CliCon.ServicioEB.EurekaServiceSoap)(this)).RegistrarDeposito(inValue);
            return retVal.Body.RegistrarDepositoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarDepositoResponse> EB_DOTNET_SOAP_CliCon.ServicioEB.EurekaServiceSoap.RegistrarDepositoAsync(EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarDepositoRequest request) {
            return base.Channel.RegistrarDepositoAsync(request);
        }
        
        public System.Threading.Tasks.Task<EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarDepositoResponse> RegistrarDepositoAsync(string cuenta, double importe) {
            EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarDepositoRequest inValue = new EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarDepositoRequest();
            inValue.Body = new EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarDepositoRequestBody();
            inValue.Body.cuenta = cuenta;
            inValue.Body.importe = importe;
            return ((EB_DOTNET_SOAP_CliCon.ServicioEB.EurekaServiceSoap)(this)).RegistrarDepositoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarRetiroResponse EB_DOTNET_SOAP_CliCon.ServicioEB.EurekaServiceSoap.RegistrarRetiro(EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarRetiroRequest request) {
            return base.Channel.RegistrarRetiro(request);
        }
        
        public string RegistrarRetiro(string cuenta, double importe) {
            EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarRetiroRequest inValue = new EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarRetiroRequest();
            inValue.Body = new EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarRetiroRequestBody();
            inValue.Body.cuenta = cuenta;
            inValue.Body.importe = importe;
            EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarRetiroResponse retVal = ((EB_DOTNET_SOAP_CliCon.ServicioEB.EurekaServiceSoap)(this)).RegistrarRetiro(inValue);
            return retVal.Body.RegistrarRetiroResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarRetiroResponse> EB_DOTNET_SOAP_CliCon.ServicioEB.EurekaServiceSoap.RegistrarRetiroAsync(EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarRetiroRequest request) {
            return base.Channel.RegistrarRetiroAsync(request);
        }
        
        public System.Threading.Tasks.Task<EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarRetiroResponse> RegistrarRetiroAsync(string cuenta, double importe) {
            EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarRetiroRequest inValue = new EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarRetiroRequest();
            inValue.Body = new EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarRetiroRequestBody();
            inValue.Body.cuenta = cuenta;
            inValue.Body.importe = importe;
            return ((EB_DOTNET_SOAP_CliCon.ServicioEB.EurekaServiceSoap)(this)).RegistrarRetiroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarTransferenciaResponse EB_DOTNET_SOAP_CliCon.ServicioEB.EurekaServiceSoap.RegistrarTransferencia(EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarTransferenciaRequest request) {
            return base.Channel.RegistrarTransferencia(request);
        }
        
        public string RegistrarTransferencia(string cuentaOrigen, string cuentaDestino, double importe) {
            EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarTransferenciaRequest inValue = new EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarTransferenciaRequest();
            inValue.Body = new EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarTransferenciaRequestBody();
            inValue.Body.cuentaOrigen = cuentaOrigen;
            inValue.Body.cuentaDestino = cuentaDestino;
            inValue.Body.importe = importe;
            EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarTransferenciaResponse retVal = ((EB_DOTNET_SOAP_CliCon.ServicioEB.EurekaServiceSoap)(this)).RegistrarTransferencia(inValue);
            return retVal.Body.RegistrarTransferenciaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarTransferenciaResponse> EB_DOTNET_SOAP_CliCon.ServicioEB.EurekaServiceSoap.RegistrarTransferenciaAsync(EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarTransferenciaRequest request) {
            return base.Channel.RegistrarTransferenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarTransferenciaResponse> RegistrarTransferenciaAsync(string cuentaOrigen, string cuentaDestino, double importe) {
            EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarTransferenciaRequest inValue = new EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarTransferenciaRequest();
            inValue.Body = new EB_DOTNET_SOAP_CliCon.ServicioEB.RegistrarTransferenciaRequestBody();
            inValue.Body.cuentaOrigen = cuentaOrigen;
            inValue.Body.cuentaDestino = cuentaDestino;
            inValue.Body.importe = importe;
            return ((EB_DOTNET_SOAP_CliCon.ServicioEB.EurekaServiceSoap)(this)).RegistrarTransferenciaAsync(inValue);
        }
    }
}
