//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EB_DOTNET_SOAP_CliCon.ServicioEB2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Movimiento", Namespace="http://schemas.datacontract.org/2004/07/WS_EB_DOTNET_SOAP.Models")]
    [System.SerializableAttribute()]
    public partial class Movimiento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CuentaCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpleadoCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ImporteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenciaCuentaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuentaCodigo {
            get {
                return this.CuentaCodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CuentaCodigoField, value) != true)) {
                    this.CuentaCodigoField = value;
                    this.RaisePropertyChanged("CuentaCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((this.NumeroField.Equals(value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string EmpleadoCodigo {
            get {
                return this.EmpleadoCodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpleadoCodigoField, value) != true)) {
                    this.EmpleadoCodigoField = value;
                    this.RaisePropertyChanged("EmpleadoCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string TipoCodigo {
            get {
                return this.TipoCodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoCodigoField, value) != true)) {
                    this.TipoCodigoField = value;
                    this.RaisePropertyChanged("TipoCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public decimal Importe {
            get {
                return this.ImporteField;
            }
            set {
                if ((this.ImporteField.Equals(value) != true)) {
                    this.ImporteField = value;
                    this.RaisePropertyChanged("Importe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string ReferenciaCuenta {
            get {
                return this.ReferenciaCuentaField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenciaCuentaField, value) != true)) {
                    this.ReferenciaCuentaField = value;
                    this.RaisePropertyChanged("ReferenciaCuenta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperacionCuentaResponse", Namespace="http://schemas.datacontract.org/2004/07/WS_EB_DOTNET_SOAP.Models")]
    [System.SerializableAttribute()]
    public partial class OperacionCuentaResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SaldoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Saldo {
            get {
                return this.SaldoField;
            }
            set {
                if ((this.SaldoField.Equals(value) != true)) {
                    this.SaldoField = value;
                    this.RaisePropertyChanged("Saldo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:eurekabank", ConfigurationName="ServicioEB2.CoreBancarioSoap")]
    public interface CoreBancarioSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:eurekabank/CoreBancarioSoap/ValidarIngreso", ReplyAction="urn:eurekabank/CoreBancarioSoap/ValidarIngresoResponse")]
        string ValidarIngreso(string usuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:eurekabank/CoreBancarioSoap/ValidarIngreso", ReplyAction="urn:eurekabank/CoreBancarioSoap/ValidarIngresoResponse")]
        System.Threading.Tasks.Task<string> ValidarIngresoAsync(string usuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:eurekabank/CoreBancarioSoap/TraerMovimientos", ReplyAction="urn:eurekabank/CoreBancarioSoap/TraerMovimientosResponse")]
        EB_DOTNET_SOAP_CliCon.ServicioEB2.Movimiento[] TraerMovimientos(string cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:eurekabank/CoreBancarioSoap/TraerMovimientos", ReplyAction="urn:eurekabank/CoreBancarioSoap/TraerMovimientosResponse")]
        System.Threading.Tasks.Task<EB_DOTNET_SOAP_CliCon.ServicioEB2.Movimiento[]> TraerMovimientosAsync(string cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:eurekabank/CoreBancarioSoap/RegDeposito", ReplyAction="urn:eurekabank/CoreBancarioSoap/RegDepositoResponse")]
        EB_DOTNET_SOAP_CliCon.ServicioEB2.OperacionCuentaResponse RegDeposito(string cuenta, decimal importe, string empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:eurekabank/CoreBancarioSoap/RegDeposito", ReplyAction="urn:eurekabank/CoreBancarioSoap/RegDepositoResponse")]
        System.Threading.Tasks.Task<EB_DOTNET_SOAP_CliCon.ServicioEB2.OperacionCuentaResponse> RegDepositoAsync(string cuenta, decimal importe, string empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:eurekabank/CoreBancarioSoap/RegRetiro", ReplyAction="urn:eurekabank/CoreBancarioSoap/RegRetiroResponse")]
        EB_DOTNET_SOAP_CliCon.ServicioEB2.OperacionCuentaResponse RegRetiro(string cuenta, decimal importe, string empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:eurekabank/CoreBancarioSoap/RegRetiro", ReplyAction="urn:eurekabank/CoreBancarioSoap/RegRetiroResponse")]
        System.Threading.Tasks.Task<EB_DOTNET_SOAP_CliCon.ServicioEB2.OperacionCuentaResponse> RegRetiroAsync(string cuenta, decimal importe, string empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:eurekabank/CoreBancarioSoap/RegTransferencia", ReplyAction="urn:eurekabank/CoreBancarioSoap/RegTransferenciaResponse")]
        EB_DOTNET_SOAP_CliCon.ServicioEB2.OperacionCuentaResponse RegTransferencia(string cuentaOrigen, string cuentaDestino, decimal importe, string empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:eurekabank/CoreBancarioSoap/RegTransferencia", ReplyAction="urn:eurekabank/CoreBancarioSoap/RegTransferenciaResponse")]
        System.Threading.Tasks.Task<EB_DOTNET_SOAP_CliCon.ServicioEB2.OperacionCuentaResponse> RegTransferenciaAsync(string cuentaOrigen, string cuentaDestino, decimal importe, string empleado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CoreBancarioSoapChannel : EB_DOTNET_SOAP_CliCon.ServicioEB2.CoreBancarioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CoreBancarioSoapClient : System.ServiceModel.ClientBase<EB_DOTNET_SOAP_CliCon.ServicioEB2.CoreBancarioSoap>, EB_DOTNET_SOAP_CliCon.ServicioEB2.CoreBancarioSoap {
        
        public CoreBancarioSoapClient() {
        }
        
        public CoreBancarioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CoreBancarioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoreBancarioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoreBancarioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ValidarIngreso(string usuario, string password) {
            return base.Channel.ValidarIngreso(usuario, password);
        }
        
        public System.Threading.Tasks.Task<string> ValidarIngresoAsync(string usuario, string password) {
            return base.Channel.ValidarIngresoAsync(usuario, password);
        }
        
        public EB_DOTNET_SOAP_CliCon.ServicioEB2.Movimiento[] TraerMovimientos(string cuenta) {
            return base.Channel.TraerMovimientos(cuenta);
        }
        
        public System.Threading.Tasks.Task<EB_DOTNET_SOAP_CliCon.ServicioEB2.Movimiento[]> TraerMovimientosAsync(string cuenta) {
            return base.Channel.TraerMovimientosAsync(cuenta);
        }
        
        public EB_DOTNET_SOAP_CliCon.ServicioEB2.OperacionCuentaResponse RegDeposito(string cuenta, decimal importe, string empleado) {
            return base.Channel.RegDeposito(cuenta, importe, empleado);
        }
        
        public System.Threading.Tasks.Task<EB_DOTNET_SOAP_CliCon.ServicioEB2.OperacionCuentaResponse> RegDepositoAsync(string cuenta, decimal importe, string empleado) {
            return base.Channel.RegDepositoAsync(cuenta, importe, empleado);
        }
        
        public EB_DOTNET_SOAP_CliCon.ServicioEB2.OperacionCuentaResponse RegRetiro(string cuenta, decimal importe, string empleado) {
            return base.Channel.RegRetiro(cuenta, importe, empleado);
        }
        
        public System.Threading.Tasks.Task<EB_DOTNET_SOAP_CliCon.ServicioEB2.OperacionCuentaResponse> RegRetiroAsync(string cuenta, decimal importe, string empleado) {
            return base.Channel.RegRetiroAsync(cuenta, importe, empleado);
        }
        
        public EB_DOTNET_SOAP_CliCon.ServicioEB2.OperacionCuentaResponse RegTransferencia(string cuentaOrigen, string cuentaDestino, decimal importe, string empleado) {
            return base.Channel.RegTransferencia(cuentaOrigen, cuentaDestino, importe, empleado);
        }
        
        public System.Threading.Tasks.Task<EB_DOTNET_SOAP_CliCon.ServicioEB2.OperacionCuentaResponse> RegTransferenciaAsync(string cuentaOrigen, string cuentaDestino, decimal importe, string empleado) {
            return base.Channel.RegTransferenciaAsync(cuentaOrigen, cuentaDestino, importe, empleado);
        }
    }
}
