//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WSEurekaSoap")]
    public interface WSEurekaSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validarIngreso", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> validarIngresoAsync(string usuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/traerMovimientos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.movimiento[]> traerMovimientosAsync(string cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/regDeposito", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.regDepositoResponse> regDepositoAsync(ServiceReference1.regDepositoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/regRetiro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.regRetiroResponse> regRetiroAsync(ServiceReference1.regRetiroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/regTransferencia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.regTransferenciaResponse> regTransferenciaAsync(ServiceReference1.regTransferenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/probarConexion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> probarConexionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/verificarTablas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> verificarTablasAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class movimiento
    {
        
        private string cuentaField;
        
        private int nromovField;
        
        private System.DateTime fechaField;
        
        private string tipoField;
        
        private string accionField;
        
        private decimal importeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string cuenta
        {
            get
            {
                return this.cuentaField;
            }
            set
            {
                this.cuentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int nromov
        {
            get
            {
                return this.nromovField;
            }
            set
            {
                this.nromovField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string accion
        {
            get
            {
                return this.accionField;
            }
            set
            {
                this.accionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal importe
        {
            get
            {
                return this.importeField;
            }
            set
            {
                this.importeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OperacionCuentaResponse
    {
        
        private int estadoField;
        
        private decimal saldoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal saldo
        {
            get
            {
                return this.saldoField;
            }
            set
            {
                this.saldoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="regDeposito", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class regDepositoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string cuenta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public decimal importe;
        
        public regDepositoRequest()
        {
        }
        
        public regDepositoRequest(string cuenta, decimal importe)
        {
            this.cuenta = cuenta;
            this.importe = importe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="regDepositoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class regDepositoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ServiceReference1.OperacionCuentaResponse OperacionCuentaResponse;
        
        public regDepositoResponse()
        {
        }
        
        public regDepositoResponse(ServiceReference1.OperacionCuentaResponse OperacionCuentaResponse)
        {
            this.OperacionCuentaResponse = OperacionCuentaResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="regRetiro", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class regRetiroRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string cuenta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public decimal importe;
        
        public regRetiroRequest()
        {
        }
        
        public regRetiroRequest(string cuenta, decimal importe)
        {
            this.cuenta = cuenta;
            this.importe = importe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="regRetiroResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class regRetiroResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ServiceReference1.OperacionCuentaResponse OperacionCuentaResponse;
        
        public regRetiroResponse()
        {
        }
        
        public regRetiroResponse(ServiceReference1.OperacionCuentaResponse OperacionCuentaResponse)
        {
            this.OperacionCuentaResponse = OperacionCuentaResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="regTransferencia", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class regTransferenciaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string cuentaOrigen;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string cuentaDestino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public decimal importe;
        
        public regTransferenciaRequest()
        {
        }
        
        public regTransferenciaRequest(string cuentaOrigen, string cuentaDestino, decimal importe)
        {
            this.cuentaOrigen = cuentaOrigen;
            this.cuentaDestino = cuentaDestino;
            this.importe = importe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="regTransferenciaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class regTransferenciaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ServiceReference1.OperacionCuentaResponse OperacionCuentaResponse;
        
        public regTransferenciaResponse()
        {
        }
        
        public regTransferenciaResponse(ServiceReference1.OperacionCuentaResponse OperacionCuentaResponse)
        {
            this.OperacionCuentaResponse = OperacionCuentaResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface WSEurekaSoapChannel : ServiceReference1.WSEurekaSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class WSEurekaSoapClient : System.ServiceModel.ClientBase<ServiceReference1.WSEurekaSoap>, ServiceReference1.WSEurekaSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WSEurekaSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WSEurekaSoapClient.GetBindingForEndpoint(endpointConfiguration), WSEurekaSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSEurekaSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WSEurekaSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSEurekaSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WSEurekaSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSEurekaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> validarIngresoAsync(string usuario, string password)
        {
            return base.Channel.validarIngresoAsync(usuario, password);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.movimiento[]> traerMovimientosAsync(string cuenta)
        {
            return base.Channel.traerMovimientosAsync(cuenta);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.regDepositoResponse> ServiceReference1.WSEurekaSoap.regDepositoAsync(ServiceReference1.regDepositoRequest request)
        {
            return base.Channel.regDepositoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.regDepositoResponse> regDepositoAsync(string cuenta, decimal importe)
        {
            ServiceReference1.regDepositoRequest inValue = new ServiceReference1.regDepositoRequest();
            inValue.cuenta = cuenta;
            inValue.importe = importe;
            return ((ServiceReference1.WSEurekaSoap)(this)).regDepositoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.regRetiroResponse> ServiceReference1.WSEurekaSoap.regRetiroAsync(ServiceReference1.regRetiroRequest request)
        {
            return base.Channel.regRetiroAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.regRetiroResponse> regRetiroAsync(string cuenta, decimal importe)
        {
            ServiceReference1.regRetiroRequest inValue = new ServiceReference1.regRetiroRequest();
            inValue.cuenta = cuenta;
            inValue.importe = importe;
            return ((ServiceReference1.WSEurekaSoap)(this)).regRetiroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.regTransferenciaResponse> ServiceReference1.WSEurekaSoap.regTransferenciaAsync(ServiceReference1.regTransferenciaRequest request)
        {
            return base.Channel.regTransferenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.regTransferenciaResponse> regTransferenciaAsync(string cuentaOrigen, string cuentaDestino, decimal importe)
        {
            ServiceReference1.regTransferenciaRequest inValue = new ServiceReference1.regTransferenciaRequest();
            inValue.cuentaOrigen = cuentaOrigen;
            inValue.cuentaDestino = cuentaDestino;
            inValue.importe = importe;
            return ((ServiceReference1.WSEurekaSoap)(this)).regTransferenciaAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<string> probarConexionAsync()
        {
            return base.Channel.probarConexionAsync();
        }
        
        public System.Threading.Tasks.Task<string> verificarTablasAsync()
        {
            return base.Channel.verificarTablasAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSEurekaSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WSEurekaSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSEurekaSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44396/ec.edu.monster.ws/WSEureka.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WSEurekaSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44396/ec.edu.monster.ws/WSEureka.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WSEurekaSoap,
            
            WSEurekaSoap12,
        }
    }
}
