//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioEB2
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Movimiento", Namespace="http://schemas.datacontract.org/2004/07/WS_EB_DOTNET_SOAP.Models")]
    public partial class Movimiento : object
    {
        
        private string CuentaCodigoField;
        
        private int NumeroField;
        
        private System.DateTime FechaField;
        
        private string EmpleadoCodigoField;
        
        private string TipoCodigoField;
        
        private decimal ImporteField;
        
        private string ReferenciaCuentaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuentaCodigo
        {
            get
            {
                return this.CuentaCodigoField;
            }
            set
            {
                this.CuentaCodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numero
        {
            get
            {
                return this.NumeroField;
            }
            set
            {
                this.NumeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime Fecha
        {
            get
            {
                return this.FechaField;
            }
            set
            {
                this.FechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string EmpleadoCodigo
        {
            get
            {
                return this.EmpleadoCodigoField;
            }
            set
            {
                this.EmpleadoCodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string TipoCodigo
        {
            get
            {
                return this.TipoCodigoField;
            }
            set
            {
                this.TipoCodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public decimal Importe
        {
            get
            {
                return this.ImporteField;
            }
            set
            {
                this.ImporteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string ReferenciaCuenta
        {
            get
            {
                return this.ReferenciaCuentaField;
            }
            set
            {
                this.ReferenciaCuentaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperacionCuentaResponse", Namespace="http://schemas.datacontract.org/2004/07/WS_EB_DOTNET_SOAP.Models")]
    public partial class OperacionCuentaResponse : object
    {
        
        private int EstadoField;
        
        private decimal SaldoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Saldo
        {
            get
            {
                return this.SaldoField;
            }
            set
            {
                this.SaldoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:eurekabank", ConfigurationName="ServicioEB2.CoreBancarioSoap")]
    public interface CoreBancarioSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:eurekabank/CoreBancarioSoap/ValidarIngreso", ReplyAction="urn:eurekabank/CoreBancarioSoap/ValidarIngresoResponse")]
        System.Threading.Tasks.Task<string> ValidarIngresoAsync(string usuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:eurekabank/CoreBancarioSoap/TraerMovimientos", ReplyAction="urn:eurekabank/CoreBancarioSoap/TraerMovimientosResponse")]
        System.Threading.Tasks.Task<ServicioEB2.Movimiento[]> TraerMovimientosAsync(string cuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:eurekabank/CoreBancarioSoap/RegDeposito", ReplyAction="urn:eurekabank/CoreBancarioSoap/RegDepositoResponse")]
        System.Threading.Tasks.Task<ServicioEB2.OperacionCuentaResponse> RegDepositoAsync(string cuenta, decimal importe, string empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:eurekabank/CoreBancarioSoap/RegRetiro", ReplyAction="urn:eurekabank/CoreBancarioSoap/RegRetiroResponse")]
        System.Threading.Tasks.Task<ServicioEB2.OperacionCuentaResponse> RegRetiroAsync(string cuenta, decimal importe, string empleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:eurekabank/CoreBancarioSoap/RegTransferencia", ReplyAction="urn:eurekabank/CoreBancarioSoap/RegTransferenciaResponse")]
        System.Threading.Tasks.Task<ServicioEB2.OperacionCuentaResponse> RegTransferenciaAsync(string cuentaOrigen, string cuentaDestino, decimal importe, string empleado);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface CoreBancarioSoapChannel : ServicioEB2.CoreBancarioSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class CoreBancarioSoapClient : System.ServiceModel.ClientBase<ServicioEB2.CoreBancarioSoap>, ServicioEB2.CoreBancarioSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CoreBancarioSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(CoreBancarioSoapClient.GetBindingForEndpoint(endpointConfiguration), CoreBancarioSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CoreBancarioSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CoreBancarioSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CoreBancarioSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CoreBancarioSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CoreBancarioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> ValidarIngresoAsync(string usuario, string password)
        {
            return base.Channel.ValidarIngresoAsync(usuario, password);
        }
        
        public System.Threading.Tasks.Task<ServicioEB2.Movimiento[]> TraerMovimientosAsync(string cuenta)
        {
            return base.Channel.TraerMovimientosAsync(cuenta);
        }
        
        public System.Threading.Tasks.Task<ServicioEB2.OperacionCuentaResponse> RegDepositoAsync(string cuenta, decimal importe, string empleado)
        {
            return base.Channel.RegDepositoAsync(cuenta, importe, empleado);
        }
        
        public System.Threading.Tasks.Task<ServicioEB2.OperacionCuentaResponse> RegRetiroAsync(string cuenta, decimal importe, string empleado)
        {
            return base.Channel.RegRetiroAsync(cuenta, importe, empleado);
        }
        
        public System.Threading.Tasks.Task<ServicioEB2.OperacionCuentaResponse> RegTransferenciaAsync(string cuentaOrigen, string cuentaDestino, decimal importe, string empleado)
        {
            return base.Channel.RegTransferenciaAsync(cuentaOrigen, cuentaDestino, importe, empleado);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_CoreBancarioSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_CoreBancarioSoap1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_CoreBancarioSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:7299/CoreBancario.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_CoreBancarioSoap1))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:5070/soap/CoreBancario.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_CoreBancarioSoap,
            
            BasicHttpBinding_CoreBancarioSoap1,
        }
    }
}
